var ACTIONS = {
    CHANGE_CURRENT_ITEM: 'CHANGE_CURRENT_ITEM',
    TOGGLE_PREVIEW_SCREEN: 'TOGGLE_PREVIEW_SCREEN',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    TOGGLE_CART_CONTENT_CONTAINER: 'TOGGLE_CART_CONTENT_CONTAINER'
}

var STRINGS = {
    VIEW_MORE: 'View Product',
    QUICK_VIEW: 'Quick View',
    CURRENCY: 'BGN',
    HEADER_WELCOME: 'Welcome to our shop!',
    ADD_TO_CART: 'Add to Cart'
}

var VARS = {
    CART_ITEMS: 'cart_items'
}