// export const RECV_ERROR = 'RECV_ERROR';
// export const REQ_DATA = 'REQ_DATA';
// export const RECV_DATA = 'RECV_DATA';

export const CHANGE_CURRENT_ITEM = 'CHANGE_CURRENT_ITEM';
export const TOGGLE_PREVIEW_SCREEN = 'TOGGLE_PREVIEW_SCREEN';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const TOGGLE_CART_CONTENT_CONTAINER = 'TOGGLE_CART_CONTENT_CONTAINER';

export const ADD_ITEM_TO_ALLITEMS = 'ADD_ITEM_TO_ALLITEMS';
export const UPDATE_ALLITEMS = 'UPDATE_ALLITEMS';

export const ADD_TO_SEARCH_RESULTS = 'ADD_TO_SEARCH_RESULTS';
export const CLEAN_SEARCH_RESULTS = 'CLEAN_SEARCH_RESULTS';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';